[project]
name = "prueba1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "django>=5.1.7",
    "pre-commit>=4.1.0",
    "ruff>=0.10.0",
]

[dependency-groups]
dev = [
    "ruff>=0.10.0",
]
