# Generated by Django 5.1.7 on 2025-03-14 00:22
"""Migración que renombra el campo 'nombre' a 'name' en Product."""

from django.db import migrations


class Migration(migrations.Migration):
    """Renombra el campo 'nombre' a 'name' en Product."""

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="nombre",
            new_name="name",
        ),
    ]
